### ISSUE TITLE
ComboBox table source behavior inconsistent

### ISSUE THREAD

**Issue by stanbrub** [deephaven/deephaven-plugins#1024]
Using _io.combo_box_ with _ui.item_table_source_ has different behavior than using _ui.combo_box_ with _ui.item_.  The scripts below are copied from the [reference doc](https://github.com/deephaven/deephaven-plugins/blob/main/plugins/ui/docs/components/combo_box.md).  The behavior of _ui.item_ is the correct behavior.

Using _ui.item_, after selecting an item and then clicking the down arrow, all items are displayed, and the selected item has a check-mark beside it.  Clicking and typing in the text field filters the list:
```
from deephaven import ui
@ui.component
def ui_combo_box_basic():
    option, set_option = ui.use_state("")
    return ui.combo_box(
        ui.item("red panda"), ui.item("cat"), ui.item("dog"), ui.item("aardvark"), 
        ui.item("kangaroo"), ui.item("snake"), ui.item("ant"), 
        label="Favorite Animal", selected_key=option, on_change=set_option,
    )
my_combo_box_basic = ui_combo_box_basic()
``` 
Using _ui.item_table_source_, after selecting an item and then clicking the down arrow, only the selected item is displayed. Clicking and typing in the text field works the same as with _ui.item_:
```
from deephaven import ui
@ui.component
def ui_combo_box_basic():
    option, set_option = ui.use_state("")

    return ui.combo_box(
        ui.item("red panda"), ui.item("cat"), ui.item("dog"), ui.item("aardvark"), 
        ui.item("kangaroo"), ui.item("snake"), ui.item("ant"), 
        label="Favorite Animal", selected_key=option, on_change=set_option,
    )
my_combo_box_basic = ui_combo_box_basic()
```
Using a workaround, behavior for the table source is identical to the _ui.item_ form:
```
from deephaven import ui, empty_table
account_icon = "vsAccount"
columns = ["Key=new Integer(i)", "Label=new String(`Display `+i)",
    "Icon=(String) account_icon",]
column_types = empty_table(20).update(columns)

items_list = [ui.item(row['Label'],key=row['Key']) for row in column_types.iter_dict()]

my_combo_box_item_list_example = ui.combo_box(
    items_list, label="User Combo box"
)
```

**Comment by mofojed** [comment]
Migrated to https://deephaven.atlassian.net/browse/DH-18087
