### ISSUE TITLE
deephaven.ui: specifying style= attribute on html element breaks web-client-ui

### ISSUE THREAD

**Issue by niloc132** [deephaven/deephaven-plugins#121]
This bug at least exists as of 9acb671.

### Steps to reproduce:
Create a simple component that draws a `deephaven.ui.html.div()`, with a `style` attribute. The documentation for `html_element` specifies that the attributes provided will be set on the html element.

### Expected:  
The element will be visible, with some css styles applied.

### Actual:
The element isn't visible, and the rest of the `#root` element is empty in the browser DOM as well.

### Example snippets:
Trivial example:
```python
import deephaven.ui as ui

from deephaven import time_table

@ui.component
def table_and_popup():
    return ui.html.div(style="")

hi = table_and_popup()
```
This should render a `<div>` with an empty style - a non-empty style also doesn't work.

I also tested with a slightly more complex structure:
```python
import deephaven.ui as ui

from deephaven import time_table

@ui.component
def table_and_popup():
    return ui.flex([
        time_table("PT1s").update("I=i"),
        ui.html.div(style="") 
    ])

hi = table_and_popup()
```

Tested on linux on both firefox and chrome.

**Comment by mofojed** [comment]
@niloc132 this is because we render HTML components using React; you should instead pass in `style` as a `dict` instead of a string, e.g.:

```py
import deephaven.ui as ui

from deephaven import time_table

@ui.component
def table_and_popup():
    return ui.html.div(style={'background': 'red', 'height': '100%'})

hi = table_and_popup()
```

I'm keeping this ticket open though because we shouldn't explode in this situation and just show an error.

**Comment by mofojed** [comment]
@niloc132 for reference: https://react.dev/reference/react-dom/components/common

**Comment by mattrunyon** [comment]
For `style` and also probably `class`/`className` we could detect and provide a better error message like React does since those are common gotchas

**Comment by mofojed** [comment]
@mattrunyon For `class` attribute, React just logs a warning in the console, but the app still renders:
![image](https://github.com/deephaven/deephaven-plugins/assets/4505624/d41d0a84-3d2b-4c8b-a8bb-b1964c5e3fa6)

However, for the `style` tag, it throws and does not render at all:
![image](https://github.com/deephaven/deephaven-plugins/assets/4505624/01377c4d-b2ec-4fe9-b008-2e758d7493f4)

I'm just suggesting we display an error in the UI - just have an [error boundary](https://react.dev/reference/react/Component#catching-rendering-errors-with-an-error-boundary) for every component.

For `class` vs. `className`, `class` is a [reserved keyword](https://docs.python.org/2.5/ref/keywords.html) and cannot be passed as a prop right now anyway - you can an invalid syntax error from python:
![image](https://github.com/deephaven/deephaven-plugins/assets/4505624/122f964b-ead1-4cdc-9a6c-e4c32b634868)

If you _were_ somehow able to specify it though, you'd just get the log error message and the object would still render.

**Comment by mofojed** [comment]
We can also do better about handling errors in callbacks, e.g.:
```
# Click the button a few times to "blow up"
from deephaven import ui

@ui.component
def counter():
    def raise_hell():
        raise Exception("hell")
    return ui.button(
        "Press to raise hell", on_press=raise_hell
    )


c = counter()
```
and:
```
# In the UI, enter an invalid number
from deephaven import empty_table, ui

@ui.component
def bad_table():
    value, set_value = ui.use_state('3')
    t = ui.use_memo(lambda: empty_table(100).update("x=i"), [])
    t2 = t.where(f"x>{value}")
    return [
        ui.text_field(value=value, on_change=set_value),
        t2
    ]


b = bad_table()
```

**Comment by mofojed** [comment]
This has been resolved and no longer breaks the web-client-ui on error.
