### ISSUE TITLE
Js content should be in same package directory

### ISSUE THREAD

**Issue by devinrsmith** [deephaven/deephaven-plugins#139]
deephaven-plugin-plotly-express has demonstrated packaging js content within a wheel. Currently, this content lives sourced in its own directory from the root, `/tmp/dpe/lib/python3.11/site-packages/js/plotly-express/`. I would have expected this content to live in the same subdirectory as the python content itself; for example `/tmp/dpe/lib64/python3.11/site-packages/deephaven/plot/express/js/`.

**Comment by mofojed** [comment]
Fixed with https://github.com/deephaven/deephaven-plugins/pull/361
