### ISSUE TITLE
Native plotly-express plots do not display with deephaven-plugin-plotly-express installed

### ISSUE THREAD

**Issue by mofojed** [deephaven/deephaven-plugins#174]
Right now if you only install deephaven-plugin-plotly-express, and you create a plot using just native plotly-express, the plot does not appear.

**Steps to Reproduce**
1. Install just the `deephaven-plugin-plotly-express`, do not install `deephaven-plugin-plotly`
2. Run the following plotly-express command to create a plotly express chart:
```python
import plotly.express as px
df = px.data.iris()
fig = px.scatter(df, x="sepal_width", y="sepal_length", color="species")
fig.show()
```

**Expected Results**
2. Plot should appear

**Actual Results**
2. Plot does not appear. Native plots are covered with `deephaven-plugin-plotly`, but that requires packaging plotly.js separately and is wasteful; we should just deprecate `deephaven-plugin-plotly` and incorporate the functionality in `deephaven-plugin-plotly-express`.

**Comment by jnumainville** [comment]
Fixed in #358
