### ISSUE TITLE
Column spacing in `ui.flex` is not as expected, and is often non-deterministic

### ISSUE THREAD

**Issue by alexpeters1208** [deephaven/deephaven-plugins#177]
When using `ui.flex` to create a two-column layout with `deephaven.ui`, the layout of the columns is not spaced 50/50 as expected. The spacing is shifted to one side or the other, and can change from run to run. Here are back-to-back runs of a layout I put together:

<img width="1039" alt="Screenshot 2023-12-15 at 2 44 27 PM" src="https://github.com/deephaven/deephaven-plugins/assets/80283343/2b4cacd7-4087-4e14-9d42-56f63a8fdc1a">
<img width="865" alt="Screenshot 2023-12-15 at 3 02 15 PM" src="https://github.com/deephaven/deephaven-plugins/assets/80283343/ce7128cb-9fec-408a-83f2-e0de2f45baac">

**Steps to reproduce**

Here is a reproducible version of my layout with the "stocks" dataset:

```
from deephaven import ui
import deephaven.plot.express as dx

stocks = dx.data.stocks()

@ui.component
def query_textbox():
    query, set_query = ui.use_state("stocks")

    return ui.flex(
        ui.text_field(value=query, on_change=set_query),
        direction="column"
    )

@ui.component
def raw_data_tab():
    return(
        ui.flex(
            ui.flex(
                ui.flex(
                    ui.text("Trips dataset"),
                    stocks,
                    direction="column",
                    flex_grow=1
                ),
                ui.flex(
                    ui.text("Stations dataset"),
                    stocks,
                    direction="column",
                    flex_grow=1
                ),
                direction="row",
                flex_grow=1
            ),
            ui.flex(
                ui.text("Input a Deephaven query here!", width="100%"),
                query_textbox(),
                flex_grow=1,
                direction="column"
            ),
            direction="column",
            flex_grow=1,
            height="100%"
        )
    )

@ui.component
def through_time_tab():
    return(
        ui.flex(
            ui.text("adfgadsf")
        )
    )

@ui.component
def through_space_tab():
    return(
        ui.flex(
            ui.text("adfgadsf")
        )
    )

@ui.component
def main_tabs():
    return ui.panel(
        ui.tabs(
            ui.tab_list(
                ui.item("Raw Data", key="Raw Data"),
                ui.item("Through Time", key="Through Time"),
                ui.item("Through Space", key="Through Space")
            ),
            ui.tab_panels(
                ui.item(raw_data_tab(), key="Raw Data"),
                ui.item(through_time_tab(), key="Through Time"),
                ui.item(through_space_tab(), key="Through Space")
            ),
            flex_grow=1
        )
    )

bikeshare = main_tabs()
```

**Expected results**

I expect the two tables side-by-side to split the space evenly by default.

**Actual results**

You can see the non-50/50 splitting, and the non-determinism in how things split. I have seen other examples of this non-determinism, where the two tables are squished together on the left side, and there's a chunk of empty space to the right.

**Versions**

 - Engine Version: 0.31.0
 - Web UI Version: 0.31.0?
 - OS: MacOS
 - Browser: Safari

**Comment by mattrunyon** [comment]
There's a handful of things here, but the main thing I'd consider a bug is we're hiding the overflow within panels by default. We shouldn't do that so it's clear here what is happening. Your 2nd table is actually expanding past the edge of the panel.

I'm not entirely sure why the tables will end up as different widths on each render with the current code, but some of the issue is missing properties. You'd need to add `flex_shrink=1` at least to both elements, but that alone won't achieve what you want. `flex_shrink` defaults to 0, so no items will shrink past their minimum content size. The other part is if you want a 50/50 split then you should apply `width: 50%` to each element in the row.

As written, your code for the row currently says "Let each item take its desired space based on contents. If there's any leftover width, equally grow both items. Never shrink either item"

**Comment by mofojed** [comment]
@mattrunyon In the screenshots, the 2nd table is not expanding past the edge of the panel; you can see the right scroll bar on the second table on the right of the panel.
The implicit sizing is screwy though. CSS Flex :muscle:

**Comment by mattrunyon** [comment]
Probably just be the branch I was on then, but it was definitely hiding overflow for me when I ran the code locally.
