### ISSUE TITLE
UI panels hiding overflow by default

### ISSUE THREAD

**Issue by mattrunyon** [deephaven/deephaven-plugins#178]
**Description**

UI panels set `overflow: hidden` by default. We shouldn't do this so it's clear to a user if their layout is overflowing. The scroll bars will be contained within the panel still.

Specifically the `.ui-portal-panel` CSS selector

**Comment by vbabich** [comment]
UI Panel parent still needs `overflow: hidden`, the child deephaven.ui wrapper should get the scroll.
