### ISSUE TITLE
Subplots do not always render correctly in flex components

### ISSUE THREAD

**Issue by alexpeters1208** [deephaven/deephaven-plugins#192]
**Description**

Figures with subplots (IE, figures created via `Figure(rows=y, columns=x)`) do not always render correctly when included in a `ui.flex()` call. The failure is not guaranteed, and may take a few re-runs of the same script to pop up. When it occurs, only the last plot in the subplot actually gets displayed, but the legend is correct, and all of the axes seem to try to overlap with each other.

**Steps to reproduce**

Here's a repro script:
```
from deephaven import ui
from deephaven import empty_table
from deephaven.plot.figure import Figure

@ui.component
def test():
    t = empty_table(100).update(["X = ii", "Y = Math.sin(X)"])
    plot = Figure(rows=1, cols=3). \
        new_chart(row=0, col=0). \
        plot_xy(series_name="1",
                t=t,
                x="X",
                y="Y"). \
        new_chart(row=0, col=1). \
        plot_xy(series_name="2",
                t=t,
                x="X",
                y="Y"). \
        new_chart(row=0, col=2). \
        plot_xy(series_name="3",
                t=t,
                x="X",
                y="Y"). \
        show()

    return ui.flex(
        ui.text("This is a block of text"),
        plot,
        direction="column",
        flex_grow=1
    )
```

**Expected results**

I expect this to produce the same figure with subplots every time:
<img width="868" alt="Screenshot 2024-01-02 at 10 17 16 AM" src="https://github.com/deephaven/deephaven-plugins/assets/80283343/084b6e3b-dd0c-4046-bb48-04ffd4fef621">

**Actual results**

Sometimes, the following incorrect plot will be produced:
<img width="868" alt="Screenshot 2024-01-02 at 10 16 50 AM" src="https://github.com/deephaven/deephaven-plugins/assets/80283343/831574e0-0045-4546-a49a-07013451c832">

**Versions**

 - Engine Version: 0.31.0
 - OS: MacOS
 - Browser: Safari

- Deephaven UI version is from `ghcr.io/mofojed/deephaven-plugins:alpha`

**Comment by jnumainville** [comment]
I'm unable to recreate the original issue. All traces are rendering as expected after running this several hundred times.

I did change one thing in the example by adding the width. If I don't add the width it's squished (see screenshot). @dsmmcken is something like setting the width expected or is there some way we could make this better?

```
from deephaven import ui
from deephaven import empty_table
from deephaven.plot.figure import Figure

@ui.component
def test():
    t = empty_table(100).update(["X = ii", "Y = Math.sin(X)"])
    plot = Figure(rows=1, cols=3). \
        new_chart(row=0, col=0). \
        plot_xy(series_name="1",
                t=t,
                x="X",
                y="Y"). \
        new_chart(row=0, col=1). \
        plot_xy(series_name="2",
                t=t,
                x="X",
                y="Y"). \
        new_chart(row=0, col=2). \
        plot_xy(series_name="3",
                t=t,
                x="X",
                y="Y"). \
        show()

    return ui.flex(
        ui.text("This is a block of text"),
        plot,
        direction="column",
        flex_grow=1,
        width="100%" # added this
    )

fig = test()
```

![Image](https://github.com/user-attachments/assets/b88c6d3d-f183-4e96-bc9f-66473020906e)

**Comment by mofojed** [comment]
I believe this is partial a result of our change to `align-items: start` on `ui.panel`: https://github.com/deephaven/deephaven-plugins/pull/604
This can be fixed by using a `ui.panel` instead of a `ui.flex`:
```python
from deephaven import ui
from deephaven import empty_table
from deephaven.plot.figure import Figure

@ui.component
def plot_test():
    t = empty_table(100).update(["X = ii", "Y = Math.sin(X)"])
    plot = Figure(rows=1, cols=3). \
        new_chart(row=0, col=0). \
        plot_xy(series_name="1",
                t=t,
                x="X",
                y="Y"). \
        new_chart(row=0, col=1). \
        plot_xy(series_name="2",
                t=t,
                x="X",
                y="Y"). \
        new_chart(row=0, col=2). \
        plot_xy(series_name="3",
                t=t,
                x="X",
                y="Y"). \
        show()

    return ui.panel(
        ui.text("This is a block of text"),
        plot,
    )

t = plot_test()
```

Still think we could do better...

**Comment by mofojed** [comment]
@dsmmcken currently making some changes to default layouting, will need to check this with his changes.

**Comment by mofojed** [comment]
Looks good with @dsmmcken 's latest changes #896 
![image](https://github.com/user-attachments/assets/6d008ebf-efbe-4c2e-a148-7d6b7ca9633c)
