### ISSUE TITLE
Improve Release process

### ISSUE THREAD

**Issue by mofojed** [deephaven/deephaven-plugins#196]
Our release process needs to be better automated and documented. Currently, it will try and publish if you tag a build, we do have a process that tries to publish the python package, but it doesn't seem to be using the correct token (see failure https://github.com/deephaven/deephaven-plugins/actions/runs/7453003735/job/20277492525). Also, it's not documented, and does not automate creating the Release and changelogs for it.
We currently automate the process in the web-client-ui repo, actions for [publishing production packages](https://github.com/deephaven/web-client-ui/blob/main/.github/workflows/publish-packages.yml), [publishing nightly builds](https://github.com/deephaven/web-client-ui/blob/main/.github/workflows/publish-nightly.yml), and [publishing alpha builds](https://github.com/deephaven/web-client-ui/blob/main/.github/workflows/publish-alpha.yml). 

- [x] #213
  - [x] Investigate existing tools that use conventional commits (which we already enforce) to do version bumping. Needs to support a monorepo.
    - [x] [Cocogitto](https://github.com/cocogitto/cocogitto)
    - [x] [commitizen](https://github.com/commitizen-tools/commitizen)
    - [x] Any other tools which may fit the bill on the [conventional commit](https://www.conventionalcommits.org/en/about/) site
  - [x] Document the process in the README
- [ ] Add a workflow dispatch action that can be manually run to publish an alpha (test/development) version of a build
- [ ] Add an action to publish a nightly build
- [x] #218

**Comment by JamesXNelson** [comment]
I'm not familiar w/ the exact npm commands you expect to be run.  Will this be effectively a copy-paste of the other repo, or are there meaningful different?  I'm also not entirely sure how to test this one.

**Comment by mofojed** [comment]
This will be meaningfully different from the other repo. Here, we have Python packages to publish as well. We've already got an action that does the build and does a publish: https://github.com/deephaven/deephaven-plugins/blob/main/.github/workflows/release-python-package.yml
But a couple problems:
- Doesn't seem to be using the correct token (see failure https://github.com/deephaven/deephaven-plugins/actions/runs/7453003735/job/20277492525)
- Doesn't do automatic version bumping or automatic changelog (we enforce conventional commits already, but no way to do a "version bump" from that)
- No way to do alpha/test builds

**Comment by JamesXNelson** [comment]
Hm, ok.  @mofojed can you give me an "explain it to me like I'm 5" description of exactly what your end goal is, and how I should test them?  I can figure out the _how_ of anything easily, but I want to be really sure about the _what_ so I don't waste time figuring out things that are obvious to you.

**Comment by mofojed** [comment]
Workflow dispatch and nightly builds aren't really recommended by PyPi, so we won't bother.
