### ISSUE TITLE
plotly-express - Update chart colors when theme changes

### ISSUE THREAD

**Issue by bmingles** [deephaven/deephaven-plugins#199]
Charts rendered by Plotly express plugin should update their colors when theme selection changes. We should be able to use the `useTheme` hook to subscribe to theme changes.

**Comment by AkshatJawne** [comment]
After testing and discussion with @bmingles and @mofojed , it appears that the issue that this ticket was aiming to solve has already been solved by https://github.com/deephaven/web-client-ui/pull/1772 , so closing this ticket.
