### ISSUE TITLE
Get deephaven.ui working in an embedded pip installed environment (iframe/Jupyter)

### ISSUE THREAD

**Issue by mofojed** [deephaven/deephaven-plugins#215]
Should be able to pip install environment doing `pip install deephaven-server jupyter jupyterlab deephaven-plugin-ui` and be able to use deephaven.ui in the pip installed environment.

Dependent on packaging JS with the Python module: #194

**Comment by mattrunyon** [comment]
`embed-widget` should add support for dashboards/layouts

- Show tab titles only if there are multiple panels
- Show tab and dashboard titles if there are multiple dashboards
- Panels/dashboards should not be closeable or renameable in either case
