### ISSUE TITLE
plotly-express plugin should work in pip-installed Deephaven

### ISSUE THREAD

**Issue by alexpeters1208** [deephaven/deephaven-plugins#219]
Currently, the plotly-express plugin does not work with pip-installed DH. @mattrunyon speculated that this is due to a lack of proper JS packaging for pip-installed DH, so figuring out #215 might also resolve this.

**Comment by alexpeters1208** [comment]
Looks like 150 was merged on Dec 20, but the last update to deephaven-plugin-plotly-express on PyPI was released on Dec 14: https://pypi.org/project/deephaven-plugin-plotly-express/

**Comment by mofojed** [comment]
Fixed with 0.3.0
