### ISSUE TITLE
deephaven.ui - default placement of newly opened components is inconsistent

### ISSUE THREAD

**Issue by mofojed** [deephaven/deephaven-plugins#230]
**Description**
Sometimes the default placement of a newly opened deephaven.ui component is incorrect and unexpected. For example, if the layout is just a row with two items, it should add the new item underneath spanning the full width. Instead, it's adding it as a third item in the row.

**Steps to reproduce**
1. Have a default layout with two items in one row, like the following:
![image](https://github.com/deephaven/deephaven-plugins/assets/4505624/ed19f658-54fb-4c84-b936-1964d97e2f4e)
2. Create a regular table:
```python
from deephaven import empty_table
t = empty_table(100)
```
3. Close the table created in the previous step.
4. Create a deephaven.ui component:
```python
from deephaven import ui

@ui.component
def Foo():
    return ui.text("Foo")

f = Foo()
```

**Expected results**
4. The component is placed in the same spot `t` was in step 2, e.g. 
![image](https://github.com/deephaven/deephaven-plugins/assets/4505624/70c22429-618b-483a-9048-469029c69434)

**Actual results**
4. Component is added on the right, e.g.
![image](https://github.com/deephaven/deephaven-plugins/assets/4505624/cfe110c0-e399-4617-8dbe-3e20d5058851)

**Additional details and attachments**

**Versions**
Engine Version: 0.33.0-SNAPSHOT
Web UI Version: 0.60.0
Java Version: 21.0.2
Barrage Version: 0.6.0
Browser Name: Chrome 120
OS Name: Linux

**Comment by mattrunyon** [comment]
This is because `useParentItem` defaults to `layoutManager.root.contentItems[0]`. The benefit of this is it prevents a layout component not wrapped in `ui.dashboard` from crashing the app because GoldenLayout throws if you try to add another item to the root.

We should default to `layoutManager.root` unless we're in a layout component. Then prefer `layoutManager.root.contentItems[0]` over just the root to prevent the crash

**Comment by mofojed** [comment]
Also take a look at `LayoutUtils.addStack`, where we prefer column: https://github.com/deephaven/web-client-ui/blob/f0ae05534532a30472bb426cfa82f9d41b1bca75/packages/dashboard/src/layout/LayoutUtils.ts#L108
