### ISSUE TITLE
Wrap layout components automatically when needed

### ISSUE THREAD

**Issue by mattrunyon** [deephaven/deephaven-plugins#233]
Currently, you must fully specify the layout for a dashboard in order for it to work properly. This makes the code unnecessarily verbose.

### Root (dashboard component)
Must have exactly 1 child (either a column or row)

### Row/Column
Children must meet exactly one of the following conditions
1. Only stacks
2. Only row/column

### Stack
Must have only panels as children (row/column is valid, but doesn't make sense from a layout perspective)

### Root (dashboard component)
- [ ] If the root does not have a singular row/column as its child, provide one. The opposite type of the children (e.g. wrap 3 rows w/ a column) or column by default

### Row/Column
- [ ] If children has some row/columns, wrap the other children in the proper row/column as needed (e.g. wrap children of a column in a row and vice versa)
- [ ] If children has no row/columns, wrap all children in stacks if needed
    - [ ] If children has some stacks, but not all, wrap the other children in stacks
    - [ ] If children has no stacks, wrap all children in stacks. `row(t1, t2)` seems more likely to be "split the row so both tables are visible" rather than "stack the tables together in the row". The stack component will then handle wrapping in panel

### Stack
- [ ] If children has row/column/stacks throw/warn 
- [ ] Wrap all children in panel as needed

**Comment by mofojed** [comment]
Related tickets:
- [#228](https://github.com/deephaven/deephaven-plugins/issues/228) Implicitly adding ui.stack
- [#230](https://github.com/deephaven/deephaven-plugins/issues/230) Default placement of new panels is inconsistent
