### ISSUE TITLE
Template for creating a Python/JS plugin

### ISSUE THREAD

**Issue by mofojed** [deephaven/deephaven-plugins#256]
As a developer, I want plugin template or cookie cutter script so that I can create a custom Python/JS plugin easily.

I want to take a look at using something like [cookiecutter](https://www.npmjs.com/package/cookiecutter) (doesn't necessarily have to be that package) for making a template. We publish a package that you can use to create a template, e.g. `npx @deephaven/create-plugin`, and then we can have templates for Theme plugins, or any other type of plugin.
Seems like the best option because it doesn't require cloning a repo to run a script.
Of course when we have python packaging up our JS plugins, we may want to use a more powerful templater (like [yeoman](https://github.com/yeoman/yeoman) or [cookiecutter](https://github.com/cookiecutter/cookiecutter)).
I just think we can do better than requiring someone clone our repo.

Previous comment for context: https://github.com/deephaven/deephaven-plugins/pull/154#issuecomment-1855962243

**Comment by jnumainville** [comment]
Fixed by #449
