### ISSUE TITLE
pydocs for slider

### ISSUE THREAD

**Issue by mofojed** [deephaven/deephaven-plugins#298]

**Comment by ethanalvizo** [comment]
@mofojed to address. Intentionally left out formatting options from spectrum component. Need to implement our own way of handling it so it can work with Deephaven formatting options as well

<img width="1001" alt="image" src="https://github.com/deephaven/deephaven-plugins/assets/55671206/af5936ea-7b5b-46b1-9326-99818599fdb9">

https://react-spectrum.adobe.com/react-spectrum/Slider.html

**Comment by mofojed** [comment]
May fit into this general formatting ticket: https://github.com/deephaven/deephaven-plugins/issues/365

**Comment by mofojed** [comment]
Fixed with https://github.com/deephaven/deephaven-plugins/pull/439
