### ISSUE TITLE
deephaven.ui default timestamp format

### ISSUE THREAD

**Issue by devinrsmith** [deephaven/deephaven-plugins#315]
deephaven.ui timestamp column does not pick up the default timestamp format.

The `transactions` component is a `ui.flex` with a Table; `t` is a simple `time_table`. `t` is using the proper defaults, while the `transactions` table does not appear to be.

![image](https://github.com/deephaven/deephaven-plugins/assets/6764691/c40a4629-9d67-487c-8ff4-bec92902954e)

Can be reproduced with https://github.com/devinrsmith/deephaven-aws-public-blockchain if necessary.

**Comment by mofojed** [comment]
A simple example:
```python
from deephaven import time_table, ui

tt = time_table("PT1s")
ui_tt = ui.table(tt)
```

<img width="415" alt="image" src="https://github.com/deephaven/deephaven-plugins/assets/4505624/f05a0b00-0b75-431a-94ee-e6f087f77e0a">

**Comment by kzk2000** [comment]
Awesome! Thanks for quick turnaround Is this in 0.33.1 or should I pull the latest edge version?On Feb 28, 2024, at 11:01 AM, Mike Bender ***@***.***> wrote:﻿
A simple example:
from deephaven import time_table, ui

tt = time_table("PT1s")
ui_tt = ui.table(tt)
image.png (view on web)

**Comment by mofojed** [comment]
@kzk2000 This is in deephaven-plugin-ui v0.8.0, if you pull the latest it should work now. Note that [your Dockerfile](https://github.com/kzk2000/deephaven-clickhouse/blob/master/docker/deephaven/Dockerfile) doesn't specify the version number, so you'll need to force it to pull again so it doesn't just take whatever version you already have cached.
