### ISSUE TITLE
deephaven.ui examples and docs - provide consistency and best practices in examples

### ISSUE THREAD

**Issue by mofojed** [deephaven/deephaven-plugins#341]
There are a couple of inconsistencies in our examples that we should iron out, and provide best practices for writing examples. A couple of things that should be ensured for consistency:
- [ ] `from deephaven import ui` instead of `import deephaven.ui as ui`
- [ ] Only one top-level import instead of importing each hook explicitly
- [ ] Provide `children` as positional args instead of as a keyword arg
- [ ] `snake_case` and prefixed with `ui_` when defining all components instead of `PascalCase` (which causes a linter error) when defining `@ui.component` functions (unlike functional components in React being `PascalCase` instead of `camelCase`)

We want readers of the documentation to focus on the content of the examples, and not get distracted by different syntaxes/inconsistencies.

**Comment by vbabich** [comment]
Let's take a survey internally

**Comment by mofojed** [comment]
Survey was taken, I've put the preferred options as the checkboxes above.

**Comment by dsmmcken** [comment]
What about a prefix in examples by convention instead of PascalCase?

```py
ui_stock_widget = [...]
```
