### ISSUE TITLE
Python builds can break when starting from dirty state

### ISSUE THREAD

**Issue by mattrunyon** [deephaven/deephaven-plugins#380]
**Description**

The Python wheel builds seem to need a clean state, but they don't provide the clean state. This can result in broken builds. In my case specifically, I was rebuilding the UI plugin locally. I built the JS, then the Python wheel. `plugins/ui/build/lib/deephaven/ui/_js/dist/index.js` did not match `/plugins/ui/src/js/dist/index.js` which I think means some old version in a build was being preserved instead of using my locally built version.

We should also clean up the readme as the instructions are out of date for building Python with the included JS. I'm not sure if we can add our own flags to the python build, but might be worth looking into a `--with-js` or something that also invokes `npm run build` within the `js` directory of that plugin before building the wheel

**Comment by mattrunyon** [comment]
Re-adding the triage label as I think this is important to fix and should not be backlogged

**Comment by jnumainville** [comment]
A pretty straightforward fix is one I put in #449 as this could be extra annoying for external plugin creators

Can add this to setup.py
```
# remove the build directory to ensure that the package is built from the latest js files
try:
    shutil.rmtree("build")
except FileNotFoundError:
    pass
```

As for building with js I think the `setup.py` could also be used
https://stackoverflow.com/questions/18725137/how-to-obtain-arguments-passed-to-setup-py-from-pip-with-install-option/53833930#53833930

**Comment by mattrunyon** [comment]
This was reverted by #680, so re-opening

It recently caused me to accidentally install an old whl of deephaven-plugin-plotly-express because I didn't catch the patch version bump from 0.11.1 to 0.11.2

**Comment by mattrunyon** [comment]
I haven't checked the `plugin_builder` script. I just know when I used `python -m build --wheel plugins/ui` it is still dirty, but if I'm not supposed to use that any more and `plugin_builder` does clean it out, then that's fine.

I had stale wheels from building 0.18 and then pulling after 0.19 and building again. Ended up w/ both 0.18 and 0.19 wheels and just running my previous install command in my DHC venv worked since 0.18 still existed

**Comment by mofojed** [comment]
@jnumainville verify if it's still causing a dirty state, close if it's fixed

**Comment by jnumainville** [comment]
@mofojed I'd expect, if not using `plugin_builder.py`, that this could break. Do you mean verify that `plugin_builder.py` works for this?

**Comment by jnumainville** [comment]
We point to using `plugin_builder.py` which I have verified clears the `dist` and `build` directories every time so that this error will not arise.
