### ISSUE TITLE
DHUI hooks should allow None where they allow Table instances

### ISSUE THREAD

**Issue by niloc132** [deephaven/deephaven-plugins#385]
Consider allowing use_table_data etc to take None and return empty/None instances, so that the table itself can be driven by other hooks/state, and can be unset without causing errors. Since hooks cannot be conditionally called, if the table was not available, the hook must be called with the `None` value, or fake a table in some way...

Personally I would support this returning `None` when the table was itself `None`, but then these hooks should return `[]` or other empty structures when the table was present but had no data.

**Comment by mattrunyon** [comment]
I'd say just always return `[]` even if table is `None`. Then the hook is simpler and consistent

If you had some case where you need to know if the table is `None`, you already have the table where you're calling the hook. So just do your checks after the hook is called

Note you can conditionally return from a component, but should not conditionally call a hook

```py
table, set_table = use_state(None)
data = use_column_data(table)

if table == None:
  return "No table provided"

if len(data) == 0:
  return "No data in the table"

return data
```

**Comment by niloc132** [comment]
I'd definitely prefer a clear distinction rather than always empty, otherwise we (users) cannot just test for the table being None or the returned value being empty - both must be tested if there is a distinction ("table is None because user hasn't populated the previous form" vs "table is empty because there are no results"). It isn't safe for the user to write code like 

```python
data = ui.use_table_data(table)
if data is None and table.size == 0:
  #...
```
because there can be a race between use_table_data and the table.size check, so now the user has to add UGP locks to safely decide what happened...
