### ISSUE TITLE
Buttons seem to not work in 0.12.0

### ISSUE THREAD

**Issue by pete-petey** [deephaven/deephaven-plugins#419]
**Description**

Anythign that creates a button in dh.ui fails to (i) render the label, and (ii) do anything when you press the button.

**Steps to reproduce**

Example scripts:
```
@ui.component
def ui_foo_bar():
    return [
        ui.heading("Click button below"),
        ui.button("Click Me!", on_press=lambda: print("Button was clicked!")),
    ]
    
foo_bar = ui_foo_bar()
```

The "submit" part of this:
```
@ui.component
def ui_form_submit():
    def handle_submit(data):
        print(f"Hello {data['name']}, you are {data['age']} years old")

    return ui.form(
        ui.text_field(default_value="Douglas", name="name"),
        ui.number_field(default_value=42, name="age"),
        ui.button("Submit", type="submit"),
        on_submit=handle_submit,
    )

my_form_submit = ui_form_submit()
```

**Expected results**
I expected to be able to see the label of the button and have interacting with the button yield an action.

**Actual results**
For the first script above:
![image](https://github.com/deephaven/deephaven-plugins/assets/76759964/8ef7c37e-a39d-40f2-8beb-1ff2879475b2)

For the second script above:
![image](https://github.com/deephaven/deephaven-plugins/assets/76759964/d1c9d5bc-bb62-49c9-9dc7-c5ff2b826f66)

**Versions**
dh.ui Version: 0.12.0

Engine Version: 0.34.0-SNAPSHOT
Web UI Version: 0.72.0
Java Version: 21.0.2
Barrage Version: 0.6.0
Browser Name: Chrome 123
OS Name: macOS 10.15.7

**Comment by mattrunyon** [comment]
Broken by an accidental prop added in https://github.com/deephaven/deephaven-plugins/pull/416/files#diff-7432f0041395d500740e1178ce8e16e98d5b562bf79fd347d887c2ade34ac8f4
