### ISSUE TITLE
Need to add a ui.picker backed by a table to the examples

### ISSUE THREAD

**Issue by mofojed** [deephaven/deephaven-plugins#438]
We need an example of ui.picker backed by a table in the examples.
Ideally we should have an example with a ticking table, where new options tick in. Would also be nice to be based off the stocks data or something similar as well.

**Comment by jnumainville** [comment]
I have some in #415, although not with the stocks data, but I could easily modify it.

**Comment by mofojed** [comment]
Already there https://github.com/deephaven/deephaven-plugins/blob/main/plugins/ui/docs/README.md#picker-table
