### ISSUE TITLE
`dependency released by user` in deephaven.ui queries

### ISSUE THREAD

**Issue by jjbrosnan** [deephaven/deephaven-plugins#456]
**Description**

When running deephaven.ui commands/code one after another, sometimes an error message will pop up in the console that says:

```
qtp1241897134-65 | i.d.s.s.SessionState | Internal Error '573fef7b-bf05-4464-9a13-46e595d293b5' dependency released by user.
```

This error does not actually break anything, but it makes it seem like something is broken.

**Steps to reproduce**

Either run the code blocks notebook `05. deephaven.ui.md` in the [demo system](https://controller.try-dh.demo.community.deephaven.io/) (IDE demo specifically) in the demo itself, or copy the contents to a local notebook and run it there.

**Expected results**

No error.

**Actual results**

The error. Nothing is actually broken (you can continue to run code just fine), but the error message makes it seem like something is wrong or the user made a mistake.

**Additional details and attachments**

**Versions**

 - Engine Version: 0.34.1
 - Web UI Version: Not sure. deephaven.ui 0.13
 - Java Version: Unsure, and whatever the demo runs.
 - Barrage Version: Unsure
 - OS: OS X
 - Browser: Chrome
 - Docker: 20.10.13

**Comment by jnumainville** [comment]
This is a legitimate warning raised, but should be at a lower log level. Regardless, this is something that needs be fixed in DHC - see DH-17415
