### ISSUE TITLE
Deprecate js-plugin-template

### ISSUE THREAD

**Issue by mofojed** [deephaven/deephaven-plugins#462]
Now that we've got the cookiecutter template, we should deprecate the [js-plugin-template](https://github.com/deephaven/js-plugin-template) and point it to the cookiecutter template instead.

Will also need to update the docs in deephaven.io.

**Comment by jnumainville** [comment]
Deprecated https://github.com/deephaven/js-plugin-template
Deprecated https://github.com/deephaven/deephaven-js-plugin-template
Adding cookiecutter link to dos https://github.com/deephaven/deephaven.io/pull/3961
