### ISSUE TITLE
Fix ui.icon_wrapper

### ISSUE THREAD

**Issue by bmingles** [deephaven/deephaven-plugins#526]
There is a `TODO:` comment in `basic.py` saying `ui.icon_wrapper` does not work. We should:
* ~Make it work~
* ~Split it out into it's own `icon_wrapper.py` module~
* ~Add a working example to the docs~
* Remove it. We should only need `ui.icon`

**Comment by vbabich** [comment]
We should have `ui.icon` only.
`ui.icon_wrapper` should be removed.
