### ISSUE TITLE
Remove `nx` dependency

### ISSUE THREAD

**Issue by bmingles** [deephaven/deephaven-plugins#560]
We currently have `useNx` enabled for lerna in the plugins repo. Unfortunately nx has optional architecture specific dependencies that intermittently cause us issues since `npm` doesn't always install optional dependencies of dependencies.

One option to fix this is to hoist the optional dependencies to the root (tried in [rejected PR #471](https://github.com/deephaven/deephaven-plugins/pull/471))

The other / preferable option would be to just remove the `nx` dependency altogether.

**Comment by mattrunyon** [comment]
I don't think we can remove the dependency entirely. It's required for lerna and lerna is what we use for running tasks.

We can disable or run w/ `NX_NON_NATIVE_HASHER=true`. It seems that platform specific package includes a Rust hasher instead of using git for hashing file changes

**Comment by bmingles** [comment]
We don't have a dependency on `nx` in web-client-ui. Removing seems to work fine

**Comment by mattrunyon** [comment]
`lerna` depends on it, but lists a range. So we have it pinned in our `package.json` for consistency

Removing it from our `package.json` just makes it an implicit dependency that we can't control the version of
