### ISSUE TITLE
Update actions to current versions

### ISSUE THREAD

**Issue by jnumainville** [deephaven/deephaven-plugins#578]
Github actions are getting some warnings due to deprecated actions

[changes](https://github.com/deephaven/deephaven-plugins/actions/runs/9668345630/job/26672349841)
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, dorny/paths-filter@v2. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

test-js / unit
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

[test-python (plotly-express) / test (3.11)](https://github.com/deephaven/deephaven-plugins/actions/runs/9668345630/job/26672352313)
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, actions/setup-python@v4. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

test-python (plotly-express) / test (3.8)
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, actions/setup-python@v4. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

[test-python (plotly-express) / test (3.12)](https://github.com/deephaven/deephaven-plugins/actions/runs/9668345630/job/26672352589)
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, actions/setup-python@v4. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

test-python (plotly-express) / test (3.9)
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, actions/setup-python@v4. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

[test-python (plotly-express) / test (3.10)](https://github.com/deephaven/deephaven-plugins/actions/runs/9668345630/job/26672351970)
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, actions/setup-python@v4. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

**Comment by mofojed** [comment]
I believe this was fixed with #638
