### ISSUE TITLE
ui.table support for standard additional spectrum props (height, width, flex_shrink etc)

### ISSUE THREAD

**Issue by dsmmcken** [deephaven/deephaven-plugins#606]

**Comment by mofojed** [comment]
@dsmmcken would you be able to use a `ui.view` to wrap this currently?

**Comment by dsmmcken** [comment]
Yeah, that is a work-around that users could use in the meantime.

**Comment by dsmmcken** [comment]
See useStyleProps from @deephaven/components which is how spectrum translates props to styles.
