### ISSUE TITLE
checkbox_group component

### ISSUE THREAD

**Issue by dsmmcken** [deephaven/deephaven-plugins#620]
`checkbox_group` was wrapped from spectrum, so it's available now but the component for it was never created

**Comment by bmingles** [comment]
We should consider including support for lists of primitives instead of just `ui.checkbox` children.

e.g.
`ui.checkbox_group('Aaa', 'Bbb', 'Ccc')`

**Comment by dsmmcken** [comment]
Realted: https://github.com/deephaven/deephaven-plugins/issues/765
