### ISSUE TITLE
ui.table DisplayColumn - allow display names to be added to columns

### ISSUE THREAD

**Issue by mofojed** [deephaven/deephaven-plugins#653]
There is a `DisplayColumn` type specified in `IrisGridModel`: https://github.com/deephaven/web-client-ui/blob/b741f4ec9819f1b3cf81ed4eb9a32d6487993f14/packages/iris-grid/src/IrisGridModel.ts#L31

**Comment by dsmmcken** [comment]
Note this is spec'ed in the design, an includes a request to support multiple display names for a single column, where it truncates to alternate names if space doesn't allow.

Ex.
| canis familiaris |
| doggy |
| dog |
