### ISSUE TITLE
Cookiecutter template - mismatch of supported engine vs .nvmrc

### ISSUE THREAD

**Issue by bmingles** [deephaven/deephaven-plugins#689]
After installing a fresh plugin template, I get the following error when running `npm install`
<img width="582" alt="image" src="https://github.com/user-attachments/assets/95aec5db-7080-4160-bcc0-e9720e056815">

Looks like the `engines` value is set to `18.13.0` but .nvmrc is set to `v20.13.1`

**Comment by vbabich** [comment]
As @mattrunyon  commented on #693 we might not want `engines` in the package.json.
