### ISSUE TITLE
Default prop values do not allow values from being inherited from parents

### ISSUE THREAD

**Issue by wusteven815** [deephaven/deephaven-plugins#801]
There are some props, like a form's `labelAlign`, which get inherited by its children. The current way to set default prop values does not allow that to happen. 

### Expected:
![image](https://github.com/user-attachments/assets/a012bab6-28e0-44a3-bcb3-a98874e4d5ab)
Since `labelAlign` is not set, `TextField` and `RadioGroup` should implicitly follow the parent `Form`'s `labelAlign="end"`.

### Actual:
![image](https://github.com/user-attachments/assets/d1bdd34d-a711-4e93-9b5b-4dec192bfcd4)
`TextField` and `RadioGroup` default back to `labelAlign="start"`

**Comment by wusteven815** [comment]
@dsmmcken 

From https://github.com/deephaven/deephaven-plugins/pull/799#pullrequestreview-2281317042

**Comment by dsmmcken** [comment]
I have no idea why that default is set? Just to document the default behaviour I guess?

It's not strictly necessary that we do that, so we could just remove it.

**Comment by vbabich** [comment]
The `labelAlign` shouldn't have a default set, we'll need to decide what the default behavior is on case by case basis.
