### ISSUE TITLE
ci: gcloud bucket upload mime-type is not being set correctly for docs

### ISSUE THREAD

**Issue by dsmmcken** [deephaven/deephaven-plugins#806]
The ci job is uploading some docs as octet stream and some as text/markdown to the cloud bucket. I have no idea why.

They should all be text/markdown, otherwise it prevents viewing the raw file if necessary.

<img width="654" alt="Screenshot 2024-09-05 at 4 25 34 PM" src="https://github.com/user-attachments/assets/1071ed4b-3ef6-4e57-a973-6ca11b7481cd">

**Comment by JamesXNelson** [comment]
Instead of letting google guess, you can explicitly set mime type when creating files using http headers:
```
gsutil -h "Content-Type:text/html" \
       -h "Cache-Control:public, max-age=3600" cp -r images \
       gs://bucket/images
```
