### ISSUE TITLE
`alignment` prop not working as intended for `ui.button_group`

### ISSUE THREAD

**Issue by AkshatJawne** [deephaven/deephaven-plugins#909]
**Description**

The `alignment` prop is not working for the button group, as setting `alignment` to "end" is resulting in the same alignment as the default (which is "start")

**Steps to reproduce**

1. Run the following snippet:

```
from deephaven import ui


@ui.component
def ui_button_group_alignment_examples():
    return [
        ui.button_group(
            ui.button("No, thanks", variant="secondary"),
            ui.button("Remind me later", variant="secondary"),
            ui.button("Rate Now", variant="primary"),
            orientation="vertical",
        ), 
        ui.button_group(
            ui.button("No, thanks", variant="secondary"),
            ui.button("Remind me later", variant="secondary"),
            ui.button("Rate Now", variant="primary"),
            orientation="vertical",
            alignment="center"
        ), 
        ui.button_group(
            ui.button("No, thanks", variant="secondary"),
            ui.button("Remind me later", variant="secondary"),
            ui.button("Rate Now", variant="primary"),
            orientation="vertical",
            alignment="end",
        ),
    ]


my_button_group_alignment_examples = ui_button_group_alignment_examples()
```

**Expected results**

The button group with the `alignment` set to "center" should resemble the following:

<img width="208" alt="Screenshot 2024-09-25 at 3 21 22 PM" src="https://github.com/user-attachments/assets/a75a1573-1377-4664-a311-a9604386daad">

The button group with the `alignment` set to "end" should resemble the following:

<img width="197" alt="Screenshot 2024-09-25 at 3 21 55 PM" src="https://github.com/user-attachments/assets/65af1046-2f8c-4230-aedf-55d5adb56bbd">

**Actual results**

All three button groups appear have the same alignment, in spite of having different values for the `alignment` prop.

**Comment by vbabich** [comment]
Might be related to https://github.com/deephaven/deephaven-plugins/pull/820
