### ISSUE TITLE
text_area and text_field do not work with only default value

### ISSUE THREAD

**Issue by wusteven815** [deephaven/deephaven-plugins#948]
**Description**

The text input is not editable if only the default value prop is provided.

**Steps to reproduce**

Use the following code:
```python
from deephaven import ui

my_text_area = ui.text_area(default_value="test")
my_text_field = ui.text_field(default_value="test")
```

Try modifying the text.

**Expected results**

Text is modified.

**Actual results**

Text is not modified.

**Versions**

@deephaven/js-plugin-ui 0.22.0

**Comment by bmingles** [comment]
This is likely caused by `defaultValue` being passed as `value` in `useTextInputProps`
https://github.com/deephaven/deephaven-plugins/blob/main/plugins/ui/src/js/src/elements/hooks/useTextInputProps.ts#L24
