### ISSUE TITLE
ui.dialog render test

### ISSUE THREAD

**Issue by dgodinez-dh** [deephaven/deephaven-plugins#952]
There is a bug in the `web-client-ui` spectrum theme that is causing the `dialog` underlay to render incorrectly. It is fixed here:
https://github.com/deephaven/web-client-ui/pull/2267
We need to wait for a new version of Core before adding dialog the the render tests otherwise they will start failing with the new version.

Other notes:
- dialogs should not be in `render_all` as they will cover other components
- they should be defaulted open
- there are 5 types of dialogs

**Comment by mofojed** [comment]
@dgodinez-dh the latest docker image should now have web version 0.97.0 so this should be doable now.

**Comment by dgodinez-dh** [comment]
@mofojed Last Friday, there was an issue with the overlay color being wrong. I think we need to fix that color before adding the render. @dsmmcken Do you know what the color should be?

**Comment by dgodinez-dh** [comment]
Fyi, I created a new issue for this https://github.com/deephaven/web-client-ui/issues/2276
